<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice - Chandresh Creation</title>
    <style>
    body {
        font-family: Arial, sans-serif;
        margin: 20px;
    }

    .invoice {
        border: 1px solid #ddd;
        padding: 20px;
        max-width: 800px;
        margin: 0 auto;
    }

    .header,
    .footer {
        background-color: #f5f5f5;
        padding: 10px;
    }

    .party-info,
    .invoice-info,
    .items,
    .total,
    .transport,
    .bank-details,
    .eway-bill {
        margin-top: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 8px;
        border-bottom: 1px solid #ddd;
        text-align: left;
    }

    th {
        background-color: #f5f5f5;
    }

    /* Center the header text */
    .header h2, .header h3 {
        text-align: center;
    }

    /* Style adjustments to align party info to the left and invoice info to the right */
    .party-info {
        width: 50%;
        float: left;
    }

    .invoice-info {
        width: 50%;
        float: right;
    }
    </style>
</head>
<body>

    <div class="invoice">
        <div class="header">
            <h2>CHANDRESH CREATION</h2>
            <p>SHOP NO U 1058 HARI OM MARKET NO 2 RING ROAD SURAT</p>
            <p>Phone: 2351035 | Mobile: 9727409044</p>
            <p>GSTIN: 24AVMPG4909R1ZZ</p>
            <h3>TAX INVOICE</h3>
        </div>
        
        <div class="party-info">
            <h4>Party: LOHIA ENTERPRISES (CAL) PVT.LTD.</h4>
            <table>
                <tr><td>Address:</td><td>166, MAHATMA GANDHI ROAD, 2ND FLOOR, KOLKATTA</td></tr>
                <tr><td>Party Mo. number:</td><td>9331014144</td></tr>
                <tr><td>GSTIN Number:</td><td>19AAACL5183A1ZQ</td></tr>
                <tr><td>State:</td><td>WEST BENGAL</td></tr>
			
            </table>
        </div>

        <div class="invoice-info">
            <table>
                <tr><td>Invoice No:</td><td>7927</td></tr>
                <tr><td>Invoice Date:</td><td>08/12/2023</td></tr>
                <tr><td>Parcel:</td><td>1.00</td></tr>
                <tr><td>State Code :</td><td>19</td></tr>
				
            </table>
        </div>
           
       

        <div class="items">
            <h3>Invoice Items</h3>
            <table>
                <tr>
                    <th>SR</th>
                    <th>Description of Goods</th>
                    <th>HSN</th>
                    <th>Pcs</th>
                    <th>Meters</th>
                    <th>UOM</th>
                    <th>Amount</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td>SHIRTING</td>
                    <td>540710</td>
                    <td>4</td>
                    <td>409.25</td>
                    <td>Li</td>
                    <td>13,218.77</td>
                </tr>
            </table>
        </div>

        <div class="total">
            <p>Total: 4 409.25</p>
        </div>

        <div class="transport">
            <h3>Transport Details</h3>
            <table>
                <tr><td>Transport:</td><td>UNIVERSALS EXPRESS</td></tr>
                <tr><td>Disc Amt:</td><td>0% | Transport Id: TSAAVPO0332J1ZB</td></tr>
                <tr><td>Add Amt:</td><td>0.00 | Station: KOLKATTA</td></tr>
                <tr><td>Taxable Value:</td><td>13,218.77</td></tr>
            </table>
        </div>

        <div class="bank-details">
            <h3>Bank Details</h3>
            <table>
                <tr><td>Bank Name:</td><td>ICICI BANK</td></tr>
                <tr><td>Bank Account No:</td><td>655705501051 | IFSC Code: IcIc0006557</td></tr>
                <tr><td>CGST Total:</td><td>0.00% 0.00 | SGST Total: 0.00% 0.00 | IGST Total: 660.94</td></tr>
                <tr><td>IRN No:</td><td>7a3dS08ba4b15866488ab4h9bdccOf3a205/d017191101ficcOOdeds644</td></tr>
                <tr><td>ACK No:</td><td>162315696282904 | ACKDT: 2023-12-09 13:25:00</td></tr>
                <tr><td>Total Amount After Tax:</td><td>13,880.00</td></tr>
            </table>
        </div>

        <div class="eway-bill">
            <h3>E-Way Bill System</h3>
            <table>
                <tr><td>E-Way Bill No:</td><td>621652526746</td></tr>
                <tr><td>E-Way Data:</td><td>09/12/2023 4:25:00 PM</td></tr>
                <tr><td>Generated By:</td><td>24AVMPG4509R1ZZ - CHANDRESH CREATION</td></tr>
                <tr><td>Valid From:</td><td>09/12/2023 4:25:00 PM (2023.00 Kms)</td></tr>
                <tr><td>Valid Until:</td><td>Not specified</td></tr>
                <tr><td>GST N of Supplier:</td><td>24AVMIPG4909R1ZZ - CHANDRESH CREATION</td></tr>
                <tr><td>Place of Dispatch:</td><td>SURAT, GUJARAT-395002</td></tr>
                <tr><td>GSTIN of Recipient:</td><td>19AAACL5183A1ZQ - LOHIA ENTERPRISES (CAL) PVT.LTD</td></tr>
                <tr><td>Place of Delivery:</td><td>KOLKATTA, WEST BENGAL-700007</td></tr>
                <tr><td>Document No:</td><td>7927</td></tr>
                <tr><td>Document Date:</td><td>08/12/2023</td></tr>
                <tr><td>Transaction Type:</td><td>Regular</td></tr>
                <tr><td>Value of Goods:</td><td>13,880.00</td></tr>
                <tr><td>HSN Code:</td><td>540710</td></tr>
            </table>
        </div>
    </div>

</body>
</html>
